name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Install dependencies
        run: go mod tidy

      - name: Test core
        run: go test ./... -v